spring:
  application:
    name: kalliope
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1h

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html,text/css,application/javascript
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
