version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    actions:
      patterns:
      - '*'
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  groups:
    maven:
      patterns:
      - '*'
- package-ecosystem: npm
  directory: /kalliope-web
  schedule:
    interval: monthly
  groups:
    angular:
      patterns:
      - '@angular*'
      - typescript
      - vitest
      - '@vitest/*'
    npm:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    security:
      applies-to: security-updates
      patterns:
      - '*'
  open-pull-requests-limit: 3
- package-ecosystem: docker
  directory: /
  schedule:
    interval: monthly
