version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      maven:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /kalliope-web
    schedule:
      interval: monthly
    groups:
      angular:
        patterns: ["@angular*"]
      npm:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
